version: '3'

services:
  fakeoai:
    build: .
    ports:
      - "8000:8000"
    environment:
      LICENSE: 你的调用凭证
      MANAGER: FakeOAI
      SOCIAL_LINK: https://github.com/FakeOAI/deploy
      NAVIGATE_LINK_LABEL: About FakeOAI
    restart: always
